name: Validate YAML

on:
  push: [main]

jobs:
  validate_yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install yamllint
        run: sudo apt-get install -y yamllint
      - name: Validate yaml files
        run: yamllint .
